#!/bin/bash -x
./setup.py build_i18n -m                   &&
#msgmerge -U po/zh_CN.po po/gwrite.pot      &&
./setup.py build &&
sudo ./setup.py install 
#sudo cp -av /usr/lib/python2.6/site-packages/gwrite* /usr/lib/python2.6/dist-packages/
