#!/usr/bin/python
# -*- coding: UTF-8 -*-
# vim:set shiftwidth=4 tabstop=4 expandtab textwidth=79:
# Author: Huang Jiahua <jhuangjiahua@gmail.com>
# License: GNU LGPL
# Last modified:

"""
"""
__revision__ = '0.1'



if __name__=="__main__":
    import gwrite.gwrite
    gwrite.gwrite.main()



